Repository Tejas1510/Athavani, pull requests merged in 2021-03, with the labels that each got.

#109 Added Bot
  .github/config.yml
Labels: GSSOC21, Level0, good first issue

#130 Updated the look of posts to match the given wireframe, fixes issue #105
  client/src/components/Posts/Posts.js
Labels: GSSOC21, Level2, accepted, frontend

#121 Issue #113 changed designof SgnIn/SignUp form and made responsive for…
  client/src/components/Auth/SignIn/SignIn.js
  client/src/components/Auth/SignIn/SignIn.module.css
  client/src/components/Auth/SignUp/SignUp.module.css
Labels: review-ongoing

#134 Create post UI
  client/src/components/Form/Form.js
  client/src/components/Form/style.js
Labels: GSSOC21, Level2, frontend

#139 Improved the background image.
  client/src/Images/Img.jpg
  client/src/index.css
Labels: GSSOC21, Level1, accepted

#140 Profile Button added
  client/src/App.js
  client/src/components/Posts/Posts.js
  client/src/style.js
Labels: review-ongoing

#145 PR template updated
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: GSSOC21, Level0, accepted

#142 Changed both submit and clear button of the form
  client/package.json
  client/src/components/Buttons/AvatarButtons.js
  client/src/components/Form/Form.js
  client/src/components/Form/style.js
Labels: GSSOC21, Level2, accepted, frontend

#155 [Backend] Handled Error after initial connection was established mongoose
  server/index.js
Labels: GSSOC21, Level1, accepted, backend

#160 Update Auto-Assign Feature
  .github/workflows/reviewer_auto_assigner.yml
Labels: GSSOC21, Level0, accepted

#154 correct responsiveness of sign up , sign in, forgot password forms
  client/src/components/Auth/Forgot/Forgot.module.css
  client/src/components/Auth/SignIn/SignIn.module.css
  client/src/components/Auth/SignUp/SignUp.module.css
Labels: GSSOC21, Level1, accepted, frontend

#166 Delete Comment and Error Corrected for Comment
  client/src/actions/posts.js
  client/src/api/index.js
  client/src/components/Posts/Post/Post.js
  client/src/constants/actionTypes.js
  client/src/reducer/posts.js
  server/controller/posts.js
  server/modules/postMessage.js
  server/routes/posts.js
Labels: GSSOC21, Level3, accepted, backend, frontend
