Repository Tejas1510/Athavani, pull requests merged in 2021-01, with the labels that each got.

#55 Updated the title of the website qnd changed the logo.
  client/.eslintcache
  client/public/favicon.ico
  client/public/index.html
  client/src/assets/logo.webp
Labels: DWOC, Level-2, accepted

#61 Added all contributors in README.md
  README.md
Labels: DWOC, Level-2, accepted

#66 Mails Rendering improved
  client/.eslintcache
  client/src/components/MailForm/Style.css
  homepage/css/animate.min.css
  server/html/mail.html
  server/package-lock.json
  server/package.json
  server/scripts/mailSender.js
Labels: DWOC, Level-3, accepted

#67 Integrate Welcome and Greeting Bot
  .github/config.yml
Labels: DWOC, Level-2

#68 Authentication Backend and Frontend
  client/.eslintcache
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/api/index.js
  client/src/components/Auth/SignIn/SignIn.js
  client/src/components/Auth/SignIn/SignIn.module.css
  client/src/components/Auth/SignUp/SignUp.js
  client/src/components/Auth/SignUp/SignUp.module.css
  client/src/components/Form/Form.js
  client/src/index.css
  client/src/index.js
  client/src/utils/validator.js
  server/controller/authentication.js
  server/index.js
  server/modules/postMessage.js
  server/modules/user.js
  server/package-lock.json
  server/package.json
  server/routes/authentication.js
Labels: DWOC, Level-4, accepted
