Repository Tejas1510/Athavani, pull requests merged in 2021-05, with the labels that each got.

#218 added new gif
  README.md
  assets/Athavani-GIF.gif
Labels: GSSOC21, Level0, design, documentation

#224 Divided header in two parts
  client/src/App.js
Labels: GSSOC21, Level2, frontend

#235 Bug: Fixed Broken Links
  client/src/components/Footer/Footer.js
Labels: GSSOC21, Level1

#229 Profile photo coming from different api
  client/src/api/index.js
  client/src/components/Profile/Profile.js
  server/controller/authentication.js
  server/routes/authentication.js
Labels: GSSOC21, Level3

#230 Private Route Added
  client/src/App.js
  client/src/components/Auth/PrivateRoutes.js
Labels: GSSOC21, Level3

#234 Password secured
  server/middleware/loginRequired.js
Labels: GSSOC21, Level2, backend

#236 SignUp link is not shown while loading
  client/src/components/Auth/SignIn/SignIn.js
Labels: GSSOC21, Level2, frontend

#240 Forms added onEnter
  client/src/components/Auth/SignIn/SignIn.js
  client/src/components/Auth/SignUp/SignUp.js
Labels: GSSOC21, Level3, frontend

#242 fastened the API by shifting image to another api
  client/src/api/index.js
  client/src/components/Footer/Footer.js
  client/src/components/Posts/Post/Post.js
  client/src/components/Profile/Profile.js
  server/controller/posts.js
  server/routes/posts.js
Labels: GSSOC21, Level3, backend, frontend

#246 On enter functionality added for subscribe modal
  client/src/components/MailForm/MailForm.js
Labels: GSSOC21, Level1, frontend

#247 Name changed
  client/src/App.js
Labels: GSSOC21, Level0

#248 Modal gets opened in all the pages
  client/src/App.js
Labels: GSSOC21, Level2, bug, frontend

#250 Alert converted to Toastify Message
  client/src/components/Form/Form.js
Labels: GSSOC21, Level2, frontend

#256 Menu added for navigation
  client/src/App.js
Labels: GSSOC21, Level2, frontend

#257 Issue solved
  client/src/components/Footer/Footer.js
Labels: GSSOC21, Level2, bug, frontend

#258 Made the required changes
  client/src/assets/camera.gif
  client/src/components/Profile/Profile.js
  client/src/components/Profile/Profile.module.css
Labels: GSSOC21, Level3, design, frontend

#260 Content is now not hidden due to the drawer
  client/src/components/Footer/Footer.js
  client/src/components/Footer/style.css
Labels: GSSOC21, Level2, frontend

#252 Edit Modal opens properly
  client/src/App.js
  client/src/components/Posts/Post/Post.js
  client/src/components/Posts/Posts.js
Labels: GSSOC21, Level2, frontend

#262 Discord button added
  client/src/assets/discordIcon.png
  client/src/components/Footer/Footer.js
  client/src/components/Footer/style.css
Labels: GSSOC21, Level1, frontend

#264 Close button added for all three modals
  client/src/App.js
  client/src/components/Posts/Post/Post.js
Labels: GSSOC21, Level2, frontend

#239 Issue solved of two background
  client/src/components/Auth/SignIn/SignIn.js
  client/src/components/Auth/SignIn/SignIn.module.css
  client/src/index.css
Labels: GSSOC21, Level2, frontend

#266 Made the required changes
  client/src/components/Profile/Profile.js
Labels: GSSOC21, Level2, frontend

#268 Added 3 feature
  client/src/components/Posts/Post/Post.js
Labels: GSSOC21, Level2, frontend

#270 Footer is now all set.
  client/src/components/Footer/Footer.js
  client/src/components/Footer/style.css
Labels: GSSOC21, Level2, frontend

#272 Messages appears on empty form submit
  client/src/components/Auth/SignIn/SignIn.js
  client/src/components/Auth/SignUp/SignUp.js
Labels: GSSOC21, Level1, frontend

#274 React Lazy Loading added
  client/src/App.js
Labels: GSSOC21, Level2, frontend

#278 Posts are aligned properly for uneven number of posts.
  client/src/components/Posts/Posts.js
  client/src/components/Profile/Profile.js
  client/src/components/Profile/Profile.module.css
Labels: GSSOC21, Level2, frontend
