Repository Tejas1510/Athavani, pull requests merged in 2021-06, with the labels that each got.

#280 Long Content is now handled
  client/src/components/Posts/Post/Post.js
  client/src/components/Posts/style.js
Labels: GSSOC21, Level2, frontend

#284 Sort Button added to the left bar
  client/src/components/Posts/Posts.js
  client/src/components/Posts/style.js
Labels: GSSOC21, Level2, frontend

#288 Tags are trimmed
  client/src/components/Posts/Post/Post.js
Labels: GSSOC21, Level1, frontend

#276 Post comes in according to the latest posts from the backend
  client/src/components/Profile/Profile.js
Labels: GSSOC21, Level2, frontend

#282 User can know the like and unlike process
  client/src/components/Posts/Post/Post.js
Labels: GSSOC21, Level2, frontend

#286 Search with Tag feature added
  client/src/components/Posts/Posts.js
Labels: GSSOC21, Level3, frontend

#293 Added transitions on buttons send otp and login
  client/src/components/Auth/SignIn/SignIn.module.css
  client/src/components/Auth/SignUp/SignUp.module.css
Labels: LGMSOC21, 🟩 Level1

#308 added links to the badges
  README.md
Labels: LGMSOC21, 🟩 Level1

#309 Added hover on social icons.
  client/src/components/Footer/style.css
Labels: LGMSOC21, 🟩 Level1

#300 Update README.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#317 Improved the UI of Create memory form
  client/src/App.js
  client/src/components/Form/Form.js
  client/src/components/Form/style.js
Labels: LGMSOC21, 🟨 Level2

#321 Refactored Open Source Program Section in README.md
  README.md
Labels: LGMSOC21, Level0

#322 Levels and Points #318
  README.md
Labels: LGMSOC21, 🟩 Level1

#324 bug fixed post update
  server/controller/posts.js
Labels: LGMSOC21, 🟥 Level4

#330 Removed Warnings
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Footer/Footer.js
  client/src/components/Form/Form.js
  client/src/components/Posts/Post/Post.js
  client/src/components/Posts/Posts.js
  client/src/components/Profile/Profile.js
  server/middleware/loginRequired.js
  server/package-lock.json
Labels: LGMSOC21, 🟧 Level3

#332 Added same hover effect to discord like twitter
  client/src/components/Footer/style.css
Labels: LGMSOC21, 🟩 Level1

#336 Sign-in & Sign-up completely Styled #310 from heet-kumar
  client/package-lock.json
  client/src/App.css
  client/src/components/Auth/SignIn/SignIn.js
  client/src/components/Auth/SignIn/SignIn.module.css
  client/src/components/Auth/SignUp/SignUp.js
  client/src/components/Auth/SignUp/SignUp.module.css
  client/src/components/Form/Form.js
Labels: LGMSOC21, 🟧 Level3

#337 create separate sidebar component and add some styles
  client/src/App.js
  client/src/components/404/Error404.js
  client/src/components/404/Error404.module.css
  client/src/components/Sidebar/sidebar.component.jsx
Labels: LGMSOC21, 🟥 Level4

#342 Add files via upload
  assets/CONTRIBUTING.md Images/Fork Repo.png
  assets/CONTRIBUTING.md Images/Issue aasign.png
  assets/CONTRIBUTING.md Images/Pull request.png
  assets/CONTRIBUTING.md Images/WorkRemotely.png
  assets/CONTRIBUTING.md Images/clone repo.png
Labels: LGMSOC21, 🟪 Level0
