Repository Tejas1510/Athavani, pull requests merged in 2021-07, with the labels that each got.

#341 Fixes broken image links
  CONTRIBUTING.md
Labels: LGMSOC21, 🟪 Level0

#346 Fixed Grammar #339
  client/src/components/Auth/SignIn/SignIn.js
Labels: LGMSOC21, 🟪 Level0

#345 Added Scrollbar #334
  client/src/App.css
Labels: LGMSOC21, 🟨 Level2

#351 UI Css Fix Done!
  client/src/App.js
  client/src/components/Auth/SignIn/SignIn.js
  client/src/components/Auth/SignIn/SignIn.module.css
  client/src/components/Auth/SignUp/SignUp.js
  client/src/components/Auth/SignUp/SignUp.module.css
  client/src/components/Footer/Footer.js
  client/src/index.css
Labels: LGMSOC21, 🟧 Level3
