Repository Tejas1510/Athavani, pull requests merged in 2021-04, with the labels that each got.

#170 Comment time
  client/src/components/Posts/Post/Post.js
  server/controller/posts.js
  server/modules/postMessage.js
Labels: GSSOC21, Level3, accepted, backend, frontend

#173 Deleting comments by admin
  client/src/components/Posts/Post/Post.js
  server/controller/posts.js
Labels: GSSOC21, Level3, accepted, backend, frontend

#177 Uploading memory error solved
  client/src/components/Form/Form.js
Labels: GSSOC21, Level2, accepted, frontend

#184 Headers and middleware
  client/src/App.js
  client/src/api/index.js
  client/src/components/Auth/SignIn/SignIn.js
  server/controller/authentication.js
  server/middleware/loginRequired.js
  server/routes/authentication.js
  server/routes/posts.js
Labels: GSSOC21, Level3, accepted, backend, frontend

#186 Comment button now sends one comment at a time
  client/src/components/Posts/Post/Post.js
Labels: GSSOC21, Level2, accepted, frontend

#188 Fixed bug - user could not delete their own comment
  client/src/components/Posts/Post/Post.js
Labels: GSSOC21, Level2, accepted, frontend

#189 Profile photo default
  client/src/App.js
  client/src/api/index.js
  client/src/assets/noProfilePhoto.jpg
Labels: GSSOC21, Level2, accepted, frontend

#194 Updated Footer.js
  client/src/components/Footer/Footer.js
Labels: GSSOC21, Level2, frontend

#183 added animation to posts
  client/.env
  client/package.json
  client/src/components/Posts/Post/Post.js
  client/src/components/Posts/Posts.js
Labels: changes-requested

#199 Signin Come back even after Login issue solved
  client/src/components/Auth/Forgot/Forgot.js
  client/src/components/Auth/SignIn/SignIn.js
  client/src/components/Auth/SignUp/SignUp.js
Labels: GSSOC21, Level2, accepted, frontend

#200 Create post modal
  client/package-lock.json
  client/src/App.js
  client/src/components/Form/Form.js
  client/src/components/Form/style.js
  client/src/components/Posts/Posts.js
Labels: review-ongoing

#202 Empty comment
  client/src/components/Auth/SignIn/SignIn.js
  client/src/components/Auth/SignUp/SignUp.js
  client/src/components/Posts/Post/Post.js
Labels: GSSOC21, Level2, accepted, bug

#206 modal created for comment section
  client/src/components/Posts/Post/Post.js
Labels: GSSOC21, Level2, accepted, frontend

#211 Center aligned footer contents
  client/src/components/Footer/Footer.js
Labels: GSSOC21, Level2, frontend, review-ongoing
